### ISSUE TITLE
json转python字典出现错误

### ISSUE THREAD

**Issue by laiww3** [cuhksz-nlp/AESINER#2]
Traceback (most recent call last):
  File "data_helper.py", line 401, in <module>
    request_features_from_stanford(data_dir, 'train')
  File "data_helper.py", line 161, in request_features_from_stanford
    results = nlp.annotate(sentence, properties=props)
  File "/home/jsj201-6/mount1/lww/AESINER-master1/corenlp.py", line 160, in annotate
    r_dict = json.loads(r.text)
  File "/home/jsj201-6/anaconda3/envs/lww/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/jsj201-6/anaconda3/envs/lww/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jsj201-6/anaconda3/envs/lww/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

是否对数据做过预处理，我用的WEIBO的数据集做的处理。只是将训练集、测试集、开发集改了名，我以为是空行符出现的错误，然后将数据中的空行删除，但也不行，不会爆出错，但是json文件为空了。请问是什么问题？

**Comment by fireindark707** [comment]
from stanfordcorenlp import StanfordCoreNLP
可能可以解決

**Comment by SomeoneNotLikeYou** [comment]
我也不知道 我用的masa和weibo也一直报错

**Comment by nyy477** [comment]
[datasets.zip](https://github.com/cuhksz-nlp/AESINER/files/7379928/datasets.zip)
同学可以直接使用这个数据试一试~
