### ISSUE TITLE
Error: sequence of length

### ISSUE THREAD

**Issue by fireindark707** [cuhksz-nlp/AESINER#3]
Traceback (most recent call last):
  File "train_zen_cn.py", line 262, in <module>
    trainer.train(load_best_model=False)
  File "AESINER-master/fastNLP/core/trainer.py", line 702, in train
    raise e
  File "AESINER-master/fastNLP/core/trainer.py", line 695, in train
    self._train()
  File "AESINER-master/fastNLP/core/trainer.py", line 854, in _train
    features = self.get_features(indices, seq_len=torch.max(batch_x.get("seq_len")).item())
  File "AESINER-master/fastNLP/core/trainer.py", line 748, in get_features
    ret_list[i] = torch.tensor(ret_list[i])
ValueError: expected sequence of length 29 at dim 1 (got 31)

請問這個該如何解決？

**Comment by nyy477** [comment]
你好，感谢对本工作的关注。
我们已经对这个bug做了修改，请重新pull一下代码。

**Comment by fireindark707** [comment]
> 你好，感谢对本工作的关注。
> 我们已经对这个bug做了修改，请重新pull一下代码。

get_chunk_mask_matrix 和 get_dep_mask_matrix 也在報類似錯誤，望統一修改，謝謝
