### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by v-chuqin** [cuhksz-nlp/AESINER#6]
非常感谢开源代码。但是我发现在执行WE数据的时候存在一些问题

Traceback (most recent call last):
  File "train_zen_cn.py", line 268, in <module>
    trainer.train(load_best_model=False)
  File "AESINER-master/fastNLP/core/trainer.py", line 702, in train
    raise e
  File "AESINER-master/fastNLP/core/trainer.py", line 695, in train
    self._train()
  File "AESINER-master/fastNLP/core/trainer.py", line 861, in _train
    dep_matrix = self.get_dep_mask_matrix(indices, seq_len=torch.max(batch_x.get("seq_len")).item())
  File "AESINER-master/fastNLP/core/trainer.py", line 796, in get_dep_mask_matrix
    ret[i][j] = 1
IndexError: list assignment index out of range

**Comment by ume-technology** [comment]
我也遇到这个问题,  老哥解决了没

**Comment by SomeoneNotLikeYou** [comment]
我也是 这里遇到了问题 你们解决了吗

**Comment by SomeoneNotLikeYou** [comment]
执行weibo数据的时候,在第一个epoch的时候出现了问题. 执行resume数据的时候,在第30个epoch的时候出现了问题, F1最高达到了95.58,并没有作者的96.6.

**Comment by thejacoblu** [comment]
同样的问题，现在解决了吗

**Comment by nyy477** [comment]
[datasets.zip](https://github.com/cuhksz-nlp/AESINER/files/7379913/datasets.zip) resume和weibo的数据集，同学可以使用这个数据集试一试~
